name: "idealflow test"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up
        uses: actions/setup-python@v2
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov
      - name: install self
        run: |
          pip install -e .
      - name: lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: test with pytest
        run: |
          pytest --cov=./idealflow
      - name: upload coverage to Codecov
        uses: codecov/codecov-action@v1
